# python -m train --config-name=longcrawl_v4-32_31m +paths.model_name=31m
defaults:
- longcrawl_base
- _self_

num_hosts: 4

mesh:
  d: 16 
  t: 1

training:
  warmup_steps: 290 
  steps:        2900 
  steps_for_lr: 2900 
  learning_rate: 7.3e-3
  tokens:
    batch: 16
    len: 8192

model:
  d_model: 256 
  n_q_per_kv: 1
  n_kv: 16 
  d_head: 64 
  d_ff: 1024 

  base:
    d_model: 256 
    n_q_per_kv: 1
    n_kv: 16 
    d_head: 64
    d_ff: 1024 

  layers: 8
  vocab: 50304
  
  rope_max_timescale: 10000

  parameterization: "sp"
  fully_aligned: false
  gamma_embed: 1.
  gamma_hidden: 1.
  gamma_unembed: 1.

  a_attn: 1.
  a_output: 1.
  zero_queries: true
  zero_unembed: true

longcrawl:
  path: "/home/clankur/data"

paths:
    root_working_dir: "gs://c4_v4-32_31m"

checkpoint_interval: 700 


